### PR TITLE
clean DC ontology

### PR DESCRIPTION
**Pull request by sarahbeenie**
cleaning

### CODE REVIEW

**Comment by cthoyt** [comment]
You need to switch this to a TSV

**Comment by ddomingof** [comment]
It's much easier like this to edit and everything because you wanna slice the ontology by groups of pathways and in excel (drive) is easier to can people can edit. I dont think it's a good idea as you can read it as excel too

**Comment by cthoyt** [comment]
There's no diff for excel files or ability to see them/edit them on GitHub. If you need to filter to certain rows, you can add an extra column instead of having different sheets.

**Comment by ddomingof** [comment]
People are going to edit them in google drive. it's easier

**Comment by cthoyt** [comment]
I'll provide a script to convert the excel sheet to TSV then

**Comment by ddomingof** [comment]
that's what i was thinking, then we check the differences on the tsv file

**Comment by cthoyt** [comment]
I'm doing a few PRs for fixing up the data and I also had some more ideas for automating some output like in some of my other recent repos

**Pull request merged**
